# Generated by Django 5.1.3 on 2024-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mymodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentconfig',
            fields=[
                ('mainid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mess', models.TextField()),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
