# Generated by Django 5.1.3 on 2024-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comentconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentconfig',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comentconfig',
            name='mainid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
