# Generated by Django 5.1.3 on 2024-12-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comentconfig_id_alter_comentconfig_mainid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentconfig',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
