# Generated by Django 5.1.3 on 2024-12-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='des',
            field=models.CharField(blank=True, max_length=15000),
        ),
        migrations.AddField(
            model_name='profile',
            name='vlog',
            field=models.IntegerField(default=0),
        ),
    ]
