# Generated by Django 5.1.3 on 2024-12-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_id_profile_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('vlog_id', models.CharField(default='default_id', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('thumbnail', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_html', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
