# Generated by Django 5.1.3 on 2024-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlog_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('like', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('views', models.BooleanField(default=False)),
                ('user_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
