# Generated by Django 5.1.3 on 2024-12-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreaction',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
