# Generated by Django 5.1.3 on 2024-12-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userreaction_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
