# Generated by Django 5.1.3 on 2024-12-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userreaction_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreaction',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
