# Generated by Django 5.1.3 on 2024-12-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userreaction_comment_alter_userreaction_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='vlog_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
