# Generated by Django 5.1.3 on 2024-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userreaction_vlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='follow',
            field=models.IntegerField(default=0),
        ),
    ]
