# Generated by Django 5.1.3 on 2024-12-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_userreaction_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreaction',
            name='follow_to',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
