# Generated by Django 5.1.3 on 2024-12-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userreaction_follow_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='user_interest',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
