# Generated by Django 5.1.3 on 2025-12-23 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_userreaction_user_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vlog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vlog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vlog',
            name='vlog_labels',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='vlog',
            name='vlog_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='thumbnail',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='title',
            field=models.CharField(max_length=800),
        ),
        migrations.CreateModel(
            name='DraftVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlog_id', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
