# Generated by Django 5.1.3 on 2026-04-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_vlog_comment_vlog_likes_vlog_views_vlog_vlog_labels_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comentconfig',
        ),
        migrations.RemoveField(
            model_name='draftvlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='UserReaction',
        ),
        migrations.DeleteModel(
            name='Vlog',
        ),
        migrations.DeleteModel(
            name='DraftVlog',
        ),
    ]
